# Common configuration for all profiles
spring:
  application:
    name: auth-service
  banner:
    location: banner.txt
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      uri: **
      database: AuthService
  mail:
    host: smtp.gmail.com
    port: 587
    username: **
    password: **
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

application:
  security:
    jwt:
      secretKey: FQvD9ODm6DYHnQMLFJlhYnxrLjGlFwx4/DftAy3vhgJpmpWQmpgrbChQqLNfj0OD
      expiration: 86400000000
      refresh-token:
        expiration: 604800000000


# Docker-specific configuration
---
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: **
      database: AuthService
  mail:
    host: smtp.gmail.com
    port: 587
    username: **
    password: **
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

application:
  security:
    jwt:
      secretKey: FQvD9ODm6DYHnQMLFJlhYnxrLjGlFwx4/DftAy3vhgJpmpWQmpgrbChQqLNfj0OD
      expiration: 86400000000
      refresh-token:
        expiration: 604800000000
